name: fed
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - ca-certificates=2025.1.31
  - freetype=2.10.4
  - future=1.0.0
  - jpeg=9d
  - lcms2=2.11
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.1.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.2
  - mkl=2020.4
  - ncurses=6.3
  - ninja=1.10.1
  - olefile=0.47
  - openssl=1.1.1w
  - pillow=8.0.1
  - pip=25.3
  - pycparser=2.22
  - python=3.9.12
  - python_abi=3.9
  - pytorch=1.7.1
  - readline=8.1.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchvision=0.8.2
  - typing_extensions=4.14.1
  - tzdata=2025c
  - wheel=0.45.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - contourpy==1.3.0
      - cryptography==46.0.3
      - cycler==0.12.1
      - docker==7.1.0
      - flask==3.0.2
      - flask-jwt-extended==4.6.0
      - flask-sqlalchemy==3.1.1
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - msgpack==1.1.2
      - multidict==6.7.0
      - numpy==1.26.4
      - nvflare==2.7.1
      - packaging==26.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyhocon==0.3.61
      - pyjwt==2.10.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.7.0
      - sqlalchemy==2.0.46
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/bk489/.conda/envs/fed
